service: update-zoom-attendance

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: ap-south-1
  memorySize: 128

functions:
  app:
    handler: wsgi.handler
    events:
      - http:
          path: "/zoom_att_weeks/{student_email}"
          method: GET
          cors: true

      - http:
          path: "/update_data"
          method: GET
          cors: true
